export const UPDATE_POPULAR = "UPDATE_POPULAR";
export const UPDATE_POPULAR_PAGE = "UPDATE_POPULAR_PAGE";
export const CONCAT_POPULAR = "CONCAT_POPULAR";
export const UPDATE_SEARCH_TEXT = "UPDATE_SEARCH_TEXT";
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
